### ISSUE TITLE
<Documentation>Prepare for week 6 presentation 

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project#10]
# **Description**
Prepare for week 6 presentation.

## SubFeature/component (optional)

- PowerPoint Slides (Zi Wang, Pin Lin) 
https://www.canva.com/design/DAFKk9wqgaw/dG63C1k7QX0PnaiQLFwvGQ/edit?utm_content=DAFKk9wqgaw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

- Speech (Junkai Feng)
- App Demo (Yibo Liu)

# **Milestones**
List of sub-features you intend to have done, and in Main, before the end of the sprint.
- [x] Finish the PPT (Aug. 29)
- [x] Finish the App Demo and testing (Aug. 30)
- [x] Prepare for speech  (Aug. 30)

**Completion Deadline:** Aug. 30

# **Documentation**

# **Members**
- Pin Lin (@Lavinia-pp )
- Junkai Feng (@KyloFeng )
- Zi Wang (@ellenWang918 )
