### ISSUE TITLE
<Task>Implement the drag and drop feature for MVP

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project#12]
# **Description**

Implement the drag and drop feature for MVP, user are able to drag the garbages and drop them into the bins on the game screen.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Research works(read documentation, watch tutorials) (Aug. 27)
- [x] Code Implementation (Aug. 29)
- [x] Debug and Testing (Aug. 30)
 
**Completion Deadline:** Aug. 30
 
# **Member**
- Yibo Liu (@rlybgithub )
- Yifan Zhu (@SuchPige )
