### ISSUE TITLE
<Design>Design UI Components - Garbage Bins

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project#13]
# **Description**
Design UI Components for the garbage bins

## SubFeature/component (optional)

- General Waste Bin
- Recycle Bin
- Green Bin

## **Examples (optional)**

# **Milestones**
List of sub-features you intend to have done, and in Main, before the end of the sprint.
- [ ] General Waste Bin (Sep. 5)
- [ ] Recycle Bin (Sep. 6)
- [ ] Green Bin (Sep. 7)
- [ ] Get Approved (Sep. 9)

**Completion Deadline:** Sep. 9

# **Extras (optional)**
- [ ] Extra components that you may implement if you get time.

# **Documentation**
[UI Component - Garbage Bins](https://github.com/UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project/wiki/UI-Component---Garbage-Bins)d

# **Members**
- Pin Lin @Lavinia-pp 
- Chenxi Li @chenxi04291 
- Zi Wang @ellenWang918

**Comment by ellenWang918** [comment]
Update the garbage bin. The high in the first version for the bin is too long to fit into the game interface.
Details: Reduce the high of each garbage bin.
![General Waste_ver1](https://user-images.githubusercontent.com/93024036/190943792-b3c579d9-4ee5-4675-bec9-9d2c79c054e5.png)
![Green Waste_ver1](https://user-images.githubusercontent.com/93024036/190943793-e51f6d79-8d39-47bc-bbfc-52478f62707e.png)
![Recycling Bin_ver1](https://user-images.githubusercontent.com/93024036/190943796-a93ecc02-7045-46ea-9ada-872bbd4370e6.png)
