### ISSUE TITLE
<Design>Design UI Components - Buttons

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project#14]
# **Description**
Design UI Components for the buttons

## SubFeature/component (optional)

- Buttons for the Start Screen
- Buttons for the Game Screen
- Buttons for the Gameover Screen
- Other Buttons

## **Examples (optional)**

# **Milestones**
List of sub-features you intend to have done, and in Main, before the end of the sprint.
- [ ] Buttons for the Start Screen (Sep. 8)
- [ ] Buttons for the Game Screen (Sep. 9)
- [ ] Buttons for the Gameover Screen (Sep. 10)
- [ ] Get Approved (Sep. 11)

**Completion Deadline:** Sep. 11

# **Extras (optional)**
- [ ] Extra components that you may implement if you get time.

# **Documentation**
[UI Component - Buttons](https://github.com/UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project/wiki/UI-Component---Buttons)

# **Members**
- Pin Lin @Lavinia-pp 
- Chenxi Li @chenxi04291 
- Zi Wang @ellenWang918
