### ISSUE TITLE
<Task> Game Navigation

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project#15]
# **Description**
Study and Implement the navigation between screens.

# **Milestones**
List of sub-features you intend to have done, and in Main, before the end of the sprint.
- [ ] Watch the tutorials (Sep. 5)
- [ ] Code Implementation (Sep. 10)
- [ ] Debug and get Approved (Sep. 11)

# **Documentation**
None

# **Members**
- Yibo Liu @rlybgithub
