### ISSUE TITLE
<Task>Implementation of Sign in/Sign up feature

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project#19]
# **Description**
**Task:** Implementation of Sign in/Sign up feature

Implementation of Sign in/Sign up feature. This feature allows the users to log in to the system with back-end authentication. This is a fundamental feature for the further development of data storage on the cloud and global leader board etc. The application of this feature will mainly be implemented with Google Firebase.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Watch tutorials (Sep. 07)
- [x] Code implementation (Sep. 10)
- [x] Test & debug (Sep. 12)
- [x] Styling(Sep. 16)
 
**Completion Deadline:** Sep. 16
 
# **Documentation**
- [Tech Frameworks and Features](https://github.com/UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project/wiki/Tech-Frameworks-and-Features)
 
# **Member**
- Yibo Liu(@rlybgithub )
- Yifan Zhu(@SuchPige )
- Zi Wang(@ellenWang918 )
