### ISSUE TITLE
<Task>Styling the Sign up and Sign in pages

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project#22]
# **Description**
**Task:** Styling the Sign up and Sign in pages

Styling the Sign up and Sign in pages
 
## **Example (optional)**

# **Dependencies**

- [ ] Sign up/Sign in Functionally works (#19 )
 
# **Milestones**
- [ ] Styling for sign up page (Sep. 16)
- [ ] Styling for sign in page (Sep. 18)
 
**Completion Deadline:** Sep. 20
 
# **Documentation**
- [UI Design Overviews](https://github.com/UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project/wiki/UI-Design-Overviews)

 
# **Member**
- Zi Wang(@ellenWang918 )
