### ISSUE TITLE
<Task>Loading the data from excel file

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project#25]
# **Description**
**Task:** Loading the data from the excel file

Loading the data from the excel file, it can retrieve all the garbage information, including the id, name, image URL, category and difficulty for each item.

# **Dependencies**
- [ ] Research on the garbage information of Brisbane(#8 )
 
# **Milestones**
- [ ] Sort the excel files (Sep. 21)
- [ ] Test data import to the application (Sep. 25)
- [ ] Implement the  code and card display(Sep. 30)
 
**Completion Deadline:** Sep. 30
 
# **Documentation**
