### ISSUE TITLE
<Design> Design Element Polishment and Finalise

### ISSUE THREAD

**Issue by ellenWang918** [UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project#27]
# **Description**
**Task:** **Polish** and **finalise** all of the design elements.

Confirm all of the design elements, updating and finalising the design guideline.
 
# **Dependencies**
All the design elements should be listed as follows:

- [ ] App Logo
- [ ] Brand Logo
- [ ] Colour Palette
- [ ] Typography
- [ ] UI
- [ ] Rubbish Icon
 
# **Milestones**
Only check the box when the element is been polished and finalised.
- [ ] App Logo (Sep. 19)
- [ ] Brand Logo (Sep. 20)
- [ ] Typography (Sep. 20)
- [ ] Colour Palette (Sep. 21)
- [ ] Rubbish Icon (Sep. 23)
- [ ] UI (Sep 25)
 
**Completion Deadline:** Sep. 25

# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Zi @ellenWang918 
- Pin @Lavinia-pp 
- Chenxi @chenxi04291 
- Yifan @SuchPige
