### ISSUE TITLE
Ethical principles

### ISSUE THREAD

**Issue by KyloFeng** [UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project#29]
# **Description**
**Task:** [Task Name](#3).

Establish game ethics, establish ethical guidelines, and ensure that our target users are not violated.
 
## **Example (optional)**
- **Part**: Depending on the task, you may want to provide some examples of how it would play out in the game. See next point for example...
- **Armour Benefits**: Players can wear different classes of armour. Armour takes damage until it breaks. Armour cannot be healed but can be replaced. If a player is wearing armour, its health is not affected when it takes damage unless the armour is broken.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] Dependency 1 (#xx)
- [ ] Dependency 2 (#xx)

e.g.
- [ ] #6
- [ ] Texture needs to be created for player wearing armour.
- [ ] Textures need to be created for partially, and then fully, broken armour.
- [ ] Mechanism needs to be implemented for armour to be placed onto map.
 

 
**Completion Deadline:** Aug. 23

 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username)
- Name (@github)
