### ISSUE TITLE
<Feature> Create the main frame of the mobile application

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project#3]
# **Description**
To create the main frame of the mobile application. The frame will contain the basic interface and allow to demo through different mobile devices.

# **Milestones**
List of sub-features you intend to have done, and in Main, before the end of the sprint.
- [x] Research on the frameworks/tools for the development (Aug. 12)
- [x] Decide the frameworks to use (Aug. 15)
- [x] Implement the basic interfaces (Aug. 22)
- [x] Evaluate the interfaces (Aug. 28)

**Completion Deadline:** Aug. 28

# **Extras (optional)**
- [x] Basic game logic as demo.
- [x] Some images integrate with the existing designs.

# **Documentation**
None

# **Members**
- Yibo Liu @rlybgithub
