### ISSUE TITLE
<Task>Loading Images for garbage cards.

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project#31]
# **Description**
**Task:** Loading Images for garbage cards.

Loading Images for garbage cards. The images path and information stored in a local json file. the card UI components will load them dynamically.

# **Dependencies**

- [ ] Sorted garbage list(include id, name, imageUrl, category) in excel file.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Check the Excel information correct (Oct. 04)
- [ ] Convert the excel file to json file (Oct. 04)
- [ ] Load the garbage information (Oct. 05)
- [ ] Generate the game card with the garbage information and image (Oct. 05)
 
**Completion Deadline:** Oct. 08
 
# **Documentation**
- [Garbage classification information](https://github.com/UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project/wiki/Garbage-classification-information)
