### ISSUE TITLE
<Task>Achieve the random card sort logic

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project#32]
# **Description**
**Task:** Achieve the random card sort logic

Achieve the random card sort logic. The garbage cards will be randomly generated on the game screen, it makes every game looks different. Once a card be placed to bin, the new card will be respawned until all the garbage list has been used. 

# **Dependencies**
Finish the loading garbage information to the cards

- [x]  loading garbage information into the cards (#31 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] feature of create randomness (Oct. 04)
- [x] setup the default cards and the cards pool(Oct. 04)
- [x] auto generate the new cards from cards pool (Oct. 05)
- [x] set the condition when all cards has been sorted(Oct .08)
- [x] test and debug(Oct .09)
 
**Completion Deadline:** Oct. 09
