### ISSUE TITLE
<Task>Code implementation of the point system

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project#33]
# **Description**
**Task:** Code implementation of the point system

Implement the point system. When player sort the cards into the right bin, they will get points. More complex point system can be upgrade along with the project going, for example when the player continuously get correct answer, they will receive extra points.

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Create the score board (Oct. 04)
- [ ] Implement the get point when correct (Oct. 05)
- [ ] Implement extra score (Oct. 11)
- [ ] Test & debug (Oct. 14)
 
**Completion Deadline:** Oct. 14
