### ISSUE TITLE
<Documentation>The Kick-starter Video scripts

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project#34]
# **Description**
**Task:** The Kick-starter Video scripts

The Kick-starter Video scripts introduced what should be contained in the video, the format and the scenarios of the video.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Idea brainstorming (Oct. 11)
- [ ] Initial sketch of the script (Oct. 12)
- [ ] Finalise the script (Oct. 15)
 
**Completion Deadline:** Oct. 14
 
# **Documentation**
