### ISSUE TITLE
<Task>Styling the Home Screen page

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project#35]
# **Description**
**Task:** The code implementation on styling the Home Screen page

# **Dependencies**

- [ ] Main Screen functionally works (#3 )
- [ ] Design of the home screen (#20 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Styling Home Screen (Oct. 15)
 
**Completion Deadline:** Oct. 15
 
# **Documentation**
- [UI Design Home Screen](https://github.com/UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project/wiki/UI-Design-Home-Screen)
