### ISSUE TITLE
<Test & Debug>Test and fix the contents of garbage cards

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project#36]
# **Description**
**Task:** Test and fix the contents of garbage cards

Play and find out the problems in the garbage cards, such as the title not matching the image, the image conflicting with the background colour, the size not being appropriate, etc. Then fix them.

# **Dependencies**

- [ ] Finish the garbage sorting game logic (#32 )
 
# **Milestones**
- [ ] Test and find out the problems (Oct. 06)
- [ ] Fix plan (Oct. 06)
- [ ] Design resources (Oct. 08)
- [ ] Fix in code (Oct. 10)
 
**Completion Deadline:** Oct. 10
