### ISSUE TITLE
<Document>Prepare for the final submission and EXPO

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project#37]
# **Description**
**Task:** Prepare for the final submission and Expo

Prepare for the final submission and Expo which includes the codebase, final documentation, kick-starter video, poster and the materials.

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Complete the codebase (Oct. 17)
- [ ] Complete the kick-starter video (Oct. 17)
- [ ] Complete the final documentation (Oct. 17)
- [ ] Prepare the surrounding materials like poster for the EXPO (Oct. 17)
 
**Completion Deadline:** Oct. 17
