### ISSUE TITLE
<Task>Add basic game logic for MVP

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco7381-Team-Nico-Nico-Ni/DECO7381-Project#6]
# **Description**
Add basic game logic for MVP, the app will allow users to select the answer for the garbage shown on the screen. Once users click the garbages button, it will show the answer is whether correct or incorrect.

## SubFeature/component (optional)
- Main screen for the game
- Verification of Correctness
- Restart Game

# **Milestones**
List of sub-features you intend to have done, and in Main, before the end of the sprint.
- [x] Main screen for the game. (Aug. 23)
- [x] Verification of Correctness(Aug. 24)
- [x] Restart the game(Aug. 24)

# **Documentation**
None

# **Members**
- Yibo Liu @rlybgithub
